import { __ } from '@wordpress/i18n';

const plus_extension = [
    {
        name: 'utitlies',
        label: __('Utitlies', 'tpebl'),
        widgets: [
            {
                name: 'she_adobe_fonts',
                label: __('Adobe Fonts', 'tpebl'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                keyword: ['Duplicate post', 'Clone post page', 'bulk copy'],
            },
            {
                name: 'she_custom_fonts_upload',
                label: __('Custom Fonts Upload', 'tpebl'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                keyword: ['Duplicate post', 'Clone post page', 'bulk copy'],
            },
            {
                name: 'she_replace_url_text',
                label: __('Replace URL & Text', 'tpebl'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                keyword: ['Duplicate post', 'Clone post page', 'bulk copy'],
            },
            {
                name: 'she_duplicate_post',
                label: __('Duplicate Post', 'tpebl'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                keyword: ['Duplicate post', 'Clone post page', 'bulk copy'],
            },
            {
                name: 'she_regenerate_thumbnails',
                label: __('Regenerate Thumbnails', 'tpebl'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                keyword: ['Duplicate post', 'Clone post page', 'bulk copy'],
            },
        ],
    },
    {
        name: 'performance',
        label: __('Performance', 'tpebl'),
        widgets: [
            {
                name: 'duplicate_post',
                label: __('Advanced Performance', 'tpebl'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                keyword: ['Duplicate post', 'Clone post page', 'bulk copy'],
            },
            {
                name: 'duplicate_post',
                label: __('Google Fonts', 'tpebl'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                keyword: ['Duplicate post', 'Clone post page', 'bulk copy'],
            },
            {
                name: 'duplicate_post',
                label: __('Disable Comments', 'tpebl'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                keyword: ['Duplicate post', 'Clone post page', 'bulk copy'],
            },
            {
                name: 'duplicate_post',
                label: __('Disable Image Sizes', 'tpebl'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                keyword: ['Duplicate post', 'Clone post page', 'bulk copy'],
            },
            {
                name: 'duplicate_post',
                label: __('Register Custom Image Sizes', 'tpebl'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                keyword: ['Duplicate post', 'Clone post page', 'bulk copy'],
            },
            {
                name: 'duplicate_post',
                label: __('Disable Icons', 'tpebl'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                keyword: ['Duplicate post', 'Clone post page', 'bulk copy'],
            },
        ],
    },
    {
        name:'security',
        label: __('Security', 'tpebl'),
        widgets: [
            {
                name: 'duplicate_post',
                label: __('Advanced Security', 'tpebl'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                keyword: ['Duplicate post','Clone post page','bulk copy'],
            },
            {
                name: 'duplicate_post',
                label: __('CAPTCHA', 'tpebl'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                keyword: ['Duplicate post','Clone post page','bulk copy'],
            },
            {
                name: 'duplicate_post',
                label: __('Custom Login URL', 'tpebl'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                keyword: ['Duplicate post','Clone post page','bulk copy'],
            },
            {
                name: 'duplicate_post',
                label: __('2-Factor Authentication', 'tpebl'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                keyword: ['Duplicate post','Clone post page','bulk copy'],
            },
            {
                name: 'duplicate_post',
                label: __('Content Protection', 'tpebl'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                keyword: ['Duplicate post','Clone post page','bulk copy'],
            },
            {
                name: 'duplicate_post',
                label: __('Login Email Notification', 'tpebl'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                keyword: ['Duplicate post','Clone post page','bulk copy'],
            },
        ],
    },
    {
        name:'admin_Interface',
        label: __('Admin Interface', 'tpebl'),
        widgets: [
            {
                name: 'duplicate_post',
                label: __('Disable Admin Settings', 'tpebl'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                keyword: ['Duplicate post','Clone post page','bulk copy'],
            },
            {
                name: 'duplicate_post',
                label: __('Branded WP Admin', 'tpebl'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                keyword: ['Duplicate post','Clone post page','bulk copy'],
            },
        ],
    }
]

export default {plus_extension };