import { __ } from '@wordpress/i18n';

const plus_extension = [
    {
        name: 'utilities',
        label: __('Utilities', 'she-header'),
        widgets: [
            {
                name: 'she_adobe_fonts',
                label: __('Adobe Fonts', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                category:'utilities',
                keyword: ['Duplicate post', 'Clone post page', 'bulk copy'],
            },
            {
                name: 'she_custom_fonts_upload',
                label: __('Custom Fonts Upload', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                category:'utilities',
                keyword: ['Duplicate post', 'Clone post page', 'bulk copy'],
            },
            {
                name: 'she_replace_url_text',
                label: __('Replace URL & Text', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                category:'utilities',
                keyword: ['Duplicate post', 'Clone post page', 'bulk copy'],
            },
            {
                name: 'she_duplicate_post',
                label: __('Duplicate Post', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                category:'utilities',
                keyword: ['Duplicate post', 'Clone post page', 'bulk copy'],
            },
            {
                name: 'she_regenerate_thumbnails',
                label: __('Regenerate Thumbnails', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'BETA',
                labelIcon: '',
                category:'utilities',
                keyword: ['Duplicate post', 'Clone post page', 'bulk copy'],
            },
        ],
    },
    {
        name: 'performance',
        label: __('Performance', 'she-header'),
        widgets: [
            {
                name: 'advanced_performance',
                label: __('Advanced Performance', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                category:'performance',
                keyword: ['Duplicate post', 'Clone post page', 'bulk copy'],
            },
            {
                name: 'google_fonts',
                label: __('Google Fonts', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                category:'performance',
                keyword: ['Duplicate post', 'Clone post page', 'bulk copy'],
            },
            {
                name: 'disable_comments',
                label: __('Disable Comments', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                category:'performance',
                keyword: ['Duplicate post', 'Clone post page', 'bulk copy'],
            },
            {
                name: 'disable_image_sizes',
                label: __('Disable Image Sizes', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                category:'performance',
                keyword: ['Duplicate post', 'Clone post page', 'bulk copy'],
            },
            {
                name: 'register_custom_image',
                label: __('Register Custom Image Sizes', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                category:'performance',
                keyword: ['Duplicate post', 'Clone post page', 'bulk copy'],
            },
            {
                name: 'disable_icons',
                label: __('Disable Icons', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                category:'performance',
                keyword: ['Duplicate post', 'Clone post page', 'bulk copy'],
            },
        ],
    },
    {
        name:'security',
        label: __('Security', 'she-header'),
        widgets: [
            {
                name: 'two-factor_authentication',
                label: __('2-Factor Authentication', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'pro',
                labelIcon: '',
                category:'security',
                keyword: ['Duplicate post','Clone post page','bulk copy'],
            },
            {
                name: 'content_protection',
                label: __('Content Protection', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'pro',
                labelIcon: '',
                category:'security',
                keyword: ['Duplicate post','Clone post page','bulk copy'],
            },
            {
                name: 'advanced_security',
                label: __('Advanced Security', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                category:'security',
                keyword: ['Duplicate post','Clone post page','bulk copy'],
            },
            {
                name: 'she_capatcha',
                label: __('CAPTCHA', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                category:'security',
                keyword: ['Duplicate post','Clone post page','bulk copy'],
            },
            {
                name: 'custom_login_url',
                label: __('Custom Login URL', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                category:'security',
                keyword: ['Duplicate post','Clone post page','bulk copy'],
            },
            {
                name: 'login_email_notification',
                label: __('Login Email Notification', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'pro',
                labelIcon: '',
                category:'security',
                keyword: ['Duplicate post','Clone post page','bulk copy'],
            },
        ],
    },
    {
        name:'admin_Interface',
        label: __('Admin Interface', 'she-header'),
        widgets: [
            {
                name: 'disable_admin_settings',
                label: __('Disable Admin Settings', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                category:'admin_interface',
                keyword: ['Duplicate post','Clone post page','bulk copy'],
            },
            {
                name: 'branded_wp_admin',
                label: __('Branded WP Admin', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'pro',
                labelIcon: '',
                category:'admin_interface',
                keyword: ['Duplicate post','Clone post page','bulk copy'],
            },
        ],
    }
]

export default {plus_extension };