import { __ } from '@wordpress/i18n';

const plus_extension = [
    {
        name: 'utilities',
        label: __('Utilities', 'she-header'),
        widgets: [
            {
                name: 'she_adobe_fonts',
                label: __('Adobe Fonts', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                category:'utilities',
                keyword: ['Duplicate post', 'Clone post page', 'bulk copy'],
            },
            {
                name: 'she_custom_fonts_upload',
                label: __('Custom Fonts Upload', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                category:'utilities',
                keyword: ['Duplicate post', 'Clone post page', 'bulk copy'],
            },
            {
                name: 'she_replace_url_text',
                label: __('Replace URL & Text', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                category:'utilities',
                keyword: ['Duplicate post', 'Clone post page', 'bulk copy'],
            },
            {
                name: 'she_duplicate_post',
                label: __('Duplicate Post', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                category:'utilities',
                keyword: ['Duplicate post', 'Clone post page', 'bulk copy'],
            },
            {
                name: 'she_regenerate_thumbnails',
                label: __('Regenerate Thumbnails', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'BETA',
                labelIcon: '',
                category:'utilities',
                keyword: ['Duplicate post', 'Clone post page', 'bulk copy'],
            },
            {
                name: 'she_smatp_email',
                label: __('SMTP Email', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/help/nexter-extension/setup-smtp-in-wordpress/',
                videoUrl: '',
                tag: 'BETA',
                labelIcon: '',
                category:'utilities',
                keyword: ['SMTP Email', 'Email configuration', 'SMTP settings'],
            },
            {
                name: 'she_replace_media',
                label: __('Replace Media', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/replace-media-files-in-wordpress/',
                videoUrl: '',
                tag: 'pro',
                labelIcon: '',
                category:'utilities',
                keyword: ['Replace Media', 'Media management', 'Media replacement'],
            },
            {
                name: 'she_content_post_order',
                label: __('Content Post Order', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/reorder-posts-in-wordpress/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                category:'utilities',
                keyword: ['Content Post Order', 'Content management', 'Post ordering'],
            },
            {
                name: 'she_taxonomy_term_order',
                label: __('Taxonomy (Term) Order', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/order-taxonomy-terms-in-wordpress/',
                videoUrl: '',
                tag: 'pro',
                labelIcon: '',
                category:'utilities',
                keyword: ['Taxonomy Term Order', 'Term management', 'Taxonomy ordering'],
            },
            {
                name: 'she_disable_gutenberg',
                label: __('Disable Gutenberg', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/disable-gutenberg-in-wordpress/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                category:'utilities',
                keyword: ['Disable Gutenberg', 'Gutenberg editor', 'Block editor'],
            },
            {
                name: 'she_custom_user_avatar',
                label: __('Custom User Avatar', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/add-custom-user-avatar-in-wordpress/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                category:'utilities',
                keyword: ['Custom User Avatar', 'User avatar', 'Profile picture'],
            },
            {
                name: 'she_public_preview_drafts',
                label: __('Public Preview for Drafts', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/enable-public-preview-for-unpublished-wordpress-posts/',
                videoUrl: '',
                tag: 'pro',
                labelIcon: '',
                category:'utilities',
                keyword: ['Public Preview for Drafts', 'Draft preview', 'Content preview'],
            },
            {
                name: 'she_rollback_manager',
                label: __('Rollback Manager', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/rollback-theme-plugin-in-wordpress/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                category:'utilities',
                keyword: ['Rollback Manager', 'Version control', 'Plugin rollback'],
            },
            {
                name: 'she_admin_role_switcher',
                label: __('Admin Role Switcher', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/view-admin-pages-site-as-non-administrator-in-wordpress/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                category:'utilities',
                keyword: ['Admin Role Switcher', 'User roles', 'Role management'],
            },
            {
                name: 'she_wp_debug_mode',
                label: __('WP Debug Mode', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/enable-debug-mode-in-wordpress/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                category:'utilities',
                keyword: ['WP Debug Mode', 'Debugging', 'Error logging'],
            },
            {
                name: 'she_redirect_404',
                label: __('Redirect 404', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/redirect-404-error-page-in-wordpress/',
                videoUrl: '',
                tag: 'freemium',
                labelIcon: '',
                category:'utilities',
                keyword: ['Redirect 404', '404 error', 'Page not found'],
            },
        ],
    },
    {
        name: 'performance',
        label: __('Performance', 'she-header'),
        widgets: [
            {
                name: 'advanced_performance',
                label: __('Advanced Performance', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                category:'performance',
                keyword: ['Duplicate post', 'Clone post page', 'bulk copy'],
            },
            {
                name: 'google_fonts',
                label: __('Google Fonts', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                category:'performance',
                keyword: ['Duplicate post', 'Clone post page', 'bulk copy'],
            },
            {
                name: 'disable_comments',
                label: __('Disable Comments', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                category:'performance',
                keyword: ['Duplicate post', 'Clone post page', 'bulk copy'],
            },
            {
                name: 'disable_image_sizes',
                label: __('Disable Image Sizes', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                category:'performance',
                keyword: ['Duplicate post', 'Clone post page', 'bulk copy'],
            },
            {
                name: 'register_custom_image',
                label: __('Register Custom Image Sizes', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                category:'performance',
                keyword: ['Duplicate post', 'Clone post page', 'bulk copy'],
            },
            {
                name: 'disable_icons',
                label: __('Disable Icons', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                category:'performance',
                keyword: ['Duplicate post', 'Clone post page', 'bulk copy'],
            },
            {
                name: 'revisions_control',
                label: __('Revisions Control', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/add-revision-control-in-wordpress-post-type/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                category:'performance',
                keyword: ['Revisions Control', 'Post revisions', 'Revision management'],
            },
            {
                name: 'heartbeat_control',
                label: __('Heartbeat Control', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/manage-heartbeat-control-api-in-wordpress/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                category:'performance',
                keyword: ['Heartbeat Control', 'WP Heartbeat', 'Performance optimization'],
            },
            {
                name: 'image_upload_optimize',
                label: __('Image Upload Optimize', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/use-image-upload-optimize/',
                videoUrl: '',
                tag: 'freemium',
                labelIcon: '',
                category:'performance',
                keyword: ['Image Upload Optimize', 'Image Optimization', 'Performance enhancement'],
            },
        ],
    },
    {
        name:'security',
        label: __('Security', 'she-header'),
        widgets: [
            {
                name: 'two-factor_authentication',
                label: __('2-Factor Authentication', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'pro',
                labelIcon: '',
                category:'security',
                keyword: ['second factor','2FA','two step verification'],
            },
            {
                name: 'content_protection',
                label: __('Content Protection', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'pro',
                labelIcon: '',
                category:'security',
                keyword: ['Content Protection','Protect content','Secure content'],
            },
            {
                name: 'advanced_security',
                label: __('Advanced Security', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                category:'security',
                keyword: ['Advanced Security','Security enhancement','Protect site'],
            },
            {
                name: 'she_capatcha',
                label: __('CAPTCHA', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                category:'security',
                keyword: ['CAPTCHA','CAPTCHA protection','Spam prevention'],
            },
            {
                name: 'custom_login_url',
                label: __('Custom Login URL', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                category:'security',
                keyword: ['Custom Login URL','Change login URL','Secure login'],
            },
            {
                name: 'login_email_notification',
                label: __('Login Email Notification', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'pro',
                labelIcon: '',
                category:'security',
                keyword: ['Login Email Notification','Email alert','Login notification'],
            },
            {
                name: 'svg_upload',
                label: __('SVG Upload', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/enable-svg-upload-in-wordpress/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                category:'security',
                keyword: ['SVG Upload','Enable SVG','Upload SVG'],
            },
            {
                name: 'limit_login_attempts',
                label: __('Limit Login Attempts', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/limit-login-attempts-in-wordpress/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                category:'security',
                keyword: ['Limit Login Attempts','Login attempt limit','Brute force protection'],
            },
        ],
    },
    {
        name:'admin_Interface',
        label: __('Admin Interface', 'she-header'),
        widgets: [
            {
                name: 'disable_admin_settings',
                label: __('Disable Admin Settings', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                category:'admin_interface',
                keyword: ['Disable admin settings','Admin settings control','Restrict admin access'],
            },
            {
                name: 'branded_wp_admin',
                label: __('Branded WP Admin', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/duplicate-post-pages-cpt-products-at-bulk-in-wordpress/',
                videoUrl: '',
                tag: 'pro',
                labelIcon: '',
                category:'admin_interface',
                keyword: ['Branded WP Admin','Branded admin','Admin branding'],
            },
            {
                name: 'clean_admin_bar',
                label: __('Clean Admin Bar', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/clean-up-the-wordpress-admin-bar/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                category:'admin_interface',
                keyword: ['Clean Admin Bar','Admin bar customization','Toolbar management'],
            },
            {
                name: 'wider_admin_menu',
                label: __('Wider Admin Menu', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/adjust-wordpress-admin-menu-width/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                category:'admin_interface',
                keyword: ['Wider Admin Menu','Admin menu width','Menu customization'],
            },
            {
                name: 'display_active_plugins_first',
                label: __('Display Active Plugins First', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/display-active-plugins-first-in-wordpress/',
                videoUrl: '',
                tag: 'pro',
                labelIcon: '',
                category:'admin_interface',
                keyword: ['Display Active Plugins First','Active plugins','Plugin management'],
            },
            {
                name: 'user_profile_clean',
                label: __('User Profile Clean', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/clean-user-profile-page-in-wordpress/',
                videoUrl: '',
                tag: 'pro',
                labelIcon: '',
                category:'admin_interface',
                keyword: ['User Profile Clean','User profile','Profile management'],
            },
            {
                name: 'wp_admin_menu_organizer',
                label: __('WP Admin Menu Organizer', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/organize-wordpress-admin-menu/',
                videoUrl: '',
                tag: 'pro',
                labelIcon: '',
                category:'admin_interface',
                keyword: ['WP Admin Menu Organizer','Admin menu','Menu management'],
            },
            {
                name: 'elementor_adfree',
                label: __('Elementor AdFree', 'she-header'),
                demoUrl: '',
                docUrl: 'https://nexterwp.com/docs/hide-elementor-banners/',
                videoUrl: '',
                tag: 'free',
                labelIcon: '',
                category:'admin_interface',
                keyword: ['Elementor AdFree','Elementor','AdFree'],
            },
        ],
    }
]

export default {plus_extension };